Fix chromium driver_path error
NoMethodError: undefined method `call' for "/snap/bin/chromium.chromedriver":String

You can `call` a `Proc` where you can't call a `String`.

actionpack/lib/action_dispatch/system_testing/browser.rb changed in the upgrade from Rails 6.0 to 6.1 which makes this fail.

https://github.com/rails/rails/blob/0919aa97260ab8240150278d3b07a1547489e3fd/actionpack/lib/action_dispatch/system_testing/browser.rb#L29-L40